# Generated by Django 2.1.7 on 2019-03-20 17:01

import django.contrib.postgres.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasmodels_size', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('alternate_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('location', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=None, null=True), blank=True, size=None)),
            ],
        ),
    ]
