# Generated by Django 2.1.7 on 2019-03-20 22:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangomen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='gasmodels_size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
    ]
