# Generated by Django 2.1.7 on 2019-03-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangomen', '0004_auto_20190323_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
    ]
