# Generated by Django 2.1.7 on 2019-03-23 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangomen', '0005_remove_order_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_situation', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state', to='djangomen.Order_State'),
        ),
    ]
